# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Marina Créativité
email: pao@marina-creativite.fr
tagline: Designer Graphique
logo: /assets/logo.svg
description: >- # this means to ignore newlines until "baseurl:"
  Que ce soit votre logo, votre charte graphique ou autres supports de communication, je m'occupe de vos fichiers qu'ils soient pour l’imprimés ou le numériques.
baseurl: "/" # the subpath of your site, e.g. /blog
author: Marina Jaquet
url: "https://marina-creativite.fr" # the base hostname & protocol for your site, e.g. http://example.com
behance_url: https://www.behance.net/marina_creativite
malt_url: https://www.malt.fr/profile/marinacreativite
linkedin_url: https://www.linkedin.com/in/jaquet-marina-creativite/
social:
  name: Marina Jaquet
  links:
    - https://www.behance.net/marina_creativite
    - https://www.malt.fr/profile/marinacreativite
    - https://www.linkedin.com/in/jaquet-marina-creativite/
locale: fr_FR
navigation:
  - text: "Mes créations"
    url: /creations
    color: "color-y"
  - text: "Qui suis-je"
    url: /apropos
    color: "color-m"
  - text: "Me contacter"
    url: /contact
    color: "color-c"
  - text: "Blog"
    url: /blog

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-compress-images
  - jekyll-seo-tag

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  svgo: false


jekyll_analytics:
  GoogleAnalytics:
    id: G-F1V2DX05WV
    anonymizeIp: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - _compress_images_cache.yml